# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-11-02 01:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.manager


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uname', models.CharField(max_length=9)),
                ('addname', models.CharField(max_length=9)),
                ('addres', models.CharField(max_length=100)),
                ('addtel', models.BigIntegerField()),
                ('addpost', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='carts',
            fields=[
                ('caid', models.AutoField(primary_key=True, serialize=False)),
                ('causname', models.CharField(max_length=9)),
                ('cartsid', models.CharField(max_length=255)),
                ('cartsellnum', models.IntegerField()),
                ('cartname', models.CharField(max_length=50)),
                ('cartimg', models.CharField(max_length=200)),
                ('cartjiage', models.IntegerField()),
                ('cartcolor', models.CharField(max_length=10, null=True)),
                ('cartsize', models.CharField(max_length=20, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Indent',
            fields=[
                ('inname', models.CharField(max_length=9, primary_key=True, serialize=False)),
                ('indsellid', models.BigIntegerField()),
                ('inseid', models.CharField(max_length=255)),
            ],
            managers=[
                ('indentk', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='indentss',
            fields=[
                ('inid', models.CharField(max_length=9, primary_key=True, serialize=False)),
                ('inname', models.CharField(max_length=9)),
                ('inaddres', models.CharField(max_length=100)),
                ('inaddtel', models.BigIntegerField()),
                ('inaddpost', models.IntegerField()),
                ('indsellid', models.BigIntegerField()),
                ('insellname', models.CharField(max_length=50)),
                ('insellimg', models.CharField(max_length=200)),
                ('inselljiage', models.IntegerField()),
                ('insellcolor', models.CharField(max_length=10, null=True)),
                ('insellsize', models.CharField(max_length=20, null=True)),
                ('insellnum', models.IntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='seller',
            fields=[
                ('sellid', models.BigIntegerField(primary_key=True, serialize=False)),
                ('sellname', models.CharField(max_length=50)),
                ('sellimg', models.CharField(max_length=200)),
                ('selljiage', models.IntegerField()),
                ('sellcolor', models.CharField(max_length=10, null=True)),
                ('sellsize', models.CharField(max_length=20, null=True)),
                ('sellnum', models.IntegerField(default=1)),
                ('selltype', models.CharField(max_length=255)),
                ('sellimgl1', models.CharField(max_length=255)),
                ('sellimgm1', models.CharField(max_length=255)),
                ('sellimgs1', models.CharField(max_length=255)),
                ('sellcomtype', models.CharField(max_length=255)),
                ('sellimgl2', models.CharField(max_length=255)),
                ('sellimgm2', models.CharField(max_length=255)),
                ('sellimgs2', models.CharField(max_length=255)),
                ('sellimgl3', models.CharField(max_length=255)),
                ('sellimgm3', models.CharField(max_length=255)),
                ('sellimgs3', models.CharField(max_length=255)),
                ('sellimgl4', models.CharField(max_length=255)),
                ('sellimgm4', models.CharField(max_length=255)),
                ('sellimgs4', models.CharField(max_length=255)),
                ('sellbrand', models.CharField(max_length=255)),
                ('selltime', models.CharField(max_length=255)),
                ('sellweight', models.CharField(max_length=255)),
                ('sellmade', models.CharField(max_length=255)),
                ('sellcpu', models.CharField(max_length=255)),
                ('selltouch', models.CharField(max_length=255)),
                ('sellface', models.CharField(max_length=255)),
                ('sellrun', models.CharField(max_length=255)),
                ('sellcamera', models.CharField(max_length=255)),
                ('sellimage1', models.CharField(max_length=255)),
                ('sellimage2', models.CharField(max_length=255)),
                ('sellimage3', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('username', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=12)),
            ],
            managers=[
                ('useru', django.db.models.manager.Manager()),
            ],
        ),
    ]
